//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS_homework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OppTable
    {
        public int Id { get; set; }
        public string Opportunity { get; set; }
        public System.DateTime OpportunityStartDate { get; set; }
        public System.DateTime OpportunityStopDate { get; set; }
        public System.DateTime OpportunityLastComp { get; set; }
        public string OpportunityCenter { get; set; }
    }
}
