//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS_homework.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class volunteer
    {
        [StringLength(45, MinimumLength = 1)]
        [Required]
        public string FirstName { get; set; }
        [StringLength(99, MinimumLength = 1)]
        [Required]
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Centers { get; set; }
        public string Skills { get; set; }
        public string Availability { get; set; }
        public string StreetAddress { get; set; }
        public string CityAddress { get; set; }
        public string StateAddress { get; set; }
        public string ZipAddress { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public string Education { get; set; }
        public string Liscenses { get; set; }
        public string ECFirstName { get; set; }
        public string ECLastName { get; set; }
        public string ECHomePhone { get; set; }
        public string ECCellPhone { get; set; }
        public string ECEmail { get; set; }
        public string ECStreetAddress { get; set; }
        public string ECCityAddress { get; set; }
        public string ECStateAddress { get; set; }
        public string ECZipcode { get; set; }
        public bool DLFile { get; set; }
        public bool SSFile { get; set; }
        [StringLength(20, MinimumLength = 6)]
        [Required]
        public string ApprovalStatus { get; set; }
    }
}
